libero/reviewer-client

.env.example
deployment/nginx.conf.template
docker-compose.yml
scripts/build-config.sh
webpack.parts.js

Closes #32 
- Added proxying for authentication route to backend auth service in webpack
- Update nginx configuration and scripts/build-config.sh to use CLIENT_AUTH_PROXY_URL

Add auth proxying

---

src/dashboard/components/Dashboard.test.tsx

See #69 for more information. This will catch the `ECONNREFUSED` errors being thrown in the console and re-throw as a warning.

catch connection refused error and re-throw warning with issue reference

---

.github/workflows/ci.yml

Still part of https://github.com/libero/publisher/issues/310 as a follow-up of https://github.com/libero/reviewer-client/pull/73. Compare https://github.com/libero/article-store/blob/master/.github/workflows/ci.yml#L93-L94
https://github.com/libero/reviewer-client/runs/375261132 failed because `.scripts` is not checked out by default by the `actions/checkout` Github Action.

Check out Git submodules

---

src/core/components/NavBar.tsx

Closes #105
The second hook was after a terminating conditional so it was running the first time with out the hook being called so when it re-rendered after login the hook order had changed. Something we need to look out for in the future.

move hook above conditional render to prevent hook order issue

---

config/reviewer-mocks/config.example.json
src/core/utils/createApolloClient.ts

Adding the `credential` line causes logs of CORS issues which prevents the dashboard from being rendered. This needs reinstating along with adding headers for Access-Control-Allow-Origin
see: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSNotSupportingCredentials
---
Linked to https://github.com/libero/reviewer/issues/687

Remove the inclusion of credentials

---

deployment/nginx.conf.template
src/core/utils/createApolloClient.ts

The token is currently set in App.tsx via a useEffect that reads the URL for a token. During this process, the app renders and so initialises the apollo client, and this can happen before the token is committed to local storage. 
Depending on the timing of this step, the token value is assigned to a variable (see here https://github.com/libero/reviewer-client/blob/35bdfa68c3c2c4479b3e46a4a0087ae6c253620d/src/core/utils/createApolloClient.ts#L21)
This can result in the token being null when it actually isn't.

Pull fresh token from storage

---

src/core/locales/en/wizard-form.json
src/initial-submission/components/FileDetailsForm.test.tsx
src/initial-submission/components/FileDetailsForm.tsx
src/initial-submission/components/FileDetailsForm2.test.tsx
src/ui/molecules/MultiFileUpload.test.tsx
src/ui/molecules/MultiFileUpload.tsx
src/ui/styles/MultiFileUpload.scss

closes libero/reviewer#709
Adds a message when the user reaches the maximum allowed supporting files.

709 - Add max supporting files reached message when max uploaded

---

src/initial-submission/components/FileDetailsForm.tsx
src/ui/molecules/MultiFileUpload.test.tsx
src/ui/molecules/MultiFileUpload.tsx
src/ui/styles/MultiFileUpload.scss

- Update Submission cache when uploading a supporting file (fixes bug with navigating between steps)
- Add pointer cursor styling to delete icon.
- Disable delete icon when upload supporting file is in progress to prevent incorrect state updates when uploads return response.
Closes libero/reviewer#780

780 - supporting upload cache

---

Dockerfile

- avoid running yarn install twice (6ish instead of 8+ minutes)
- only copy dist instead of all of app (30MB instead of 100MB image)

Speed up Dockerfile

---

browsertests.Dockerfile
tests/browser-tests/Minimal.browser.ts
tests/test-entry.sh

Setting the envvar "TEST_FIXTURE" will select only that named test fixture to run. Otherwise all the tests will run.
Closes #libero/reviewer#1067

Enable selectable tests with env var TEST_FIXTURE

---

tests/test-entry.sh

If passed a list of files testrunner appears to only run the first one.
This doesn't match the documentation...
By putting the glob in quotes the shell doesn't expand it.
Globbing is then handled by testcafe.

fix: test-entry.sh glob

---

src/login/utils/tokenUtils.ts

Closes https://github.com/libero/reviewer/issues/1109
After review and consideration - this is the simplest solution that won't impact the code requiring a top level state or similar. This also happens to be the solution used for invalid tokens at the ApolloClient initialisation routine found here https://github.com/libero/reviewer-client/blob/master/src/core/utils/createApolloClient.ts#L44

Redirect if token is invalid

---

src/initial-submission/components/DisclosureForm.tsx
src/initial-submission/components/SubmissionWizard.tsx
src/initial-submission/graphql.ts

Closes https://github.com/libero/reviewer/issues/1120 as well as:
- Pull disclosure details from graphql
- Disclosure boolean was not showing as checked even if true when pull from the initialValues
- triggers save on disclosure page before dialog opening
- fixes submit query

Disclosure page + submission bug 

---

src/initial-submission/components/FileDetailsForm.test.tsx

Based on this stack overflow (https://stackoverflow.com/questions/60495903/testing-react-contenteditable-with-react-testing-library+&cd=1&hl=en&ct=clnk&gl=uk) which points to two discussions https://github.com/testing-library/dom-testing-library/pull/235 and https://github.com/jsdom/jsdom/issues/1670
It’s not possible to simulate events on a contenteditable div within a js-dom context. This is a limit of js-dom itself. This is a known issue since 2016.
To save the test, the following was reviewed  - modifying the test to click the button but the value of the coverLetter would still be null as it requires that DOM event -> dispatchTranscation -> props.onChange to modify the state of coverLetter. 
Closes https://github.com/libero/reviewer/issues/1149

Remove test due to js-dom limits

---

.github/workflows/ci.yml
README.md

- only run saucelab tests if on 'master' or '[run-saucelabs]' is part of PR message
- alert #libero-reviewer-tech if pipeline fails on merge to master
- run tests in series as individual invocations of testcafe
Serial execution of the tests is necessary, as the testcafe saucelabs plugin's retry functionality does not behave as expected.
This has been recorded as a tech-debt issue: https://github.com/libero/reviewer/issues/1215
Closes: https://github.com/libero/reviewer/issues/1213

limit saucelabs to master

---

.github/workflows/ci.yml

Turns out github actions can't run be set up to run a job if other jobs fail... This should notify on failure in saucelabs or failure to push the image.

fix slack notify on failure

---

src/ui/atoms/Feedback.tsx
src/ui/styles/Feedback.scss

Closes https://github.com/libero/reviewer/issues/1402
The error seems to have been caused by a null ref. The simplest solution was to ensure the element exists and use css to hide it.

Error bar scroll issue on Safari

---

src/static-pages/styles/required-info-table.scss
src/static-pages/styles/static-page.scss

Closes libero/reviewer#1438 
This will reintroduce libero/reviewer#1440 due to a strange bug where chrome applies overflow-y on the x axis of a grid column.

fix styling for table

---

tests/page-objects/EditorPage.ts
tests/page-objects/FilesPage.ts

Attempt to fix e2e test failures when asserting on external call responses.

Add longer timeouts to integration points

---

public/locales/en/wizard-form.json
src/initial-submission/components/EditorsForm.tsx

Updated various pieces of text in the submission wizard as per the Editorial teams requirements.

fix: static text updates in the editors section of the initial submission wizard

---

Makefile

On mac, the following produces an error:
```
$ date --utc +%Y%m%d.%H%M
date: illegal option -- -
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
[-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
```
I believe the `--utc` flag can be exchanged for `-u` and work in both environments.
```
$ date -u +%Y%m%d.%H%M
20210319.0943
```

fix: date utc flag that works on linux and mac os

---

browsertests.Dockerfile

A recent testcafe release (either official docker image or the dependency itself) has caused issues with running the `--no-sandbox` argument on `master`. This PR pins the two to `testcafe:1.14.2`

Pin testcafe dep and image version

---

browsertests.Dockerfile
public/index.html

Cookiebot has a feature that automatically scans the site on a monthly frequency and determines which scripts it should block. Since the most recent scan at the start of october, it's started to incorrectly block some scripts and as such the page fails to load until the banner is dismissed. [We're not the only ones caught out by this](https://support.cookiebot.com/hc/en-us/community/posts/360007744680-Cookiebot-blocks-every-script-on-website?page=2#comments), and doesn't paint Cookiebot that well as a stable solution.
I've updated the code to rely on [manually marking the scripts against the consent topics that they relate to](https://www.cookiebot.com/en/manual-implementation/), which resolved the issue with the banner and got the CookieBot tests passing again.
This then surfaced …

fix: cookiebot is blocking the login page from loading
