libero/reviewer-client

src/ui/hooks/useDebounce.ts, src/ui/hooks/useElementSize.ts, src/ui/molecules/ManuscriptUpload.test.tsx, src/ui/molecules/ManuscriptUpload.tsx, src/ui/molecules/PeoplePickerSelector.test.tsx, src/ui/molecules/PeoplePickerSelector.tsx, src/ui/molecules/PersonPod.tsx, src/ui/molecules/SearchField.test.tsx, src/ui/molecules/SearchField.tsx, src/ui/organisms/PeoplePicker.tsx, src/ui/stories/molecules/PeoplePickerSelector.stories.tsx, src/ui/stories/molecules/SelectedOption.stories.tsx, src/ui/stories/organisms/PeoplePicker.stories.tsx
=> fix the linting issues in client

src/core/styles/_config.scss, src/core/styles/index.scss, src/login/components/Login.tsx, src/login/styles/login.scss, src/ui/atoms/Paragraph.test.tsx, src/ui/atoms/Paragraph.tsx, src/ui/styles/ImageWithAttributions.scss, src/ui/styles/Paragraph.scss, src/ui/styles/TwoColumnLayout.scss
Added some other styling fixes that were accidentally introduced when the paragraph component was ported over.
=> Fix login styles

src/core/components/NavBar.test.tsx, src/ui/atoms/Button.test.tsx, src/ui/atoms/Checkbox.test.tsx, src/ui/atoms/Modal.test.tsx, src/ui/atoms/MultilineTextField.test.tsx, src/ui/atoms/Paragraph.test.tsx, src/ui/atoms/Pod.test.tsx, src/ui/atoms/SelectField.test.tsx, src/ui/atoms/SelectField.tsx, src/ui/atoms/TextField.test.tsx, src/ui/atoms/TwoColumnLayout.test.tsx, src/ui/molecules/BurgerMenu.test.tsx, src/ui/molecules/ExtendedToggle.test.tsx, src/ui/molecules/ManuscriptUpload.test.tsx, src/ui/molecules/Menu.test.tsx, src/ui/molecules/OrcidDetails.test.tsx, src/ui/molecules/PeoplePickerSelector.test.tsx, src/ui/molecules/PersonPod.test.tsx, src/ui/molecules/ProgressBar.test.tsx, src/ui/molecules/SearchField.test.tsx, src/ui/molecules/SelectedOption.test.tsx, src/ui/molecules/SelectedPeopleList.test.tsx, src/ui/molecules/Toggle.test.tsx, src/ui/organisms/PeoplePicker.test.tsx
Add unit tests to test components with both minimum required props and all possible props.
=> 314 - render tests

src/core/components/App.tsx, src/core/components/NavBar.test.tsx, src/core/utils/i18n.ts, src/dashboard/components/Routes.test.tsx, src/initial-submission/components/Routes.test.tsx, src/login/components/Login.tsx, src/ui/molecules/PeoplePickerSelector.test.tsx, src/ui/stories/molecules/PeoplePickerSelector.stories.tsx, src/ui/stories/organisms/PeoplePicker.stories.tsx
Locally I experienced some lint errors while preparing https://github.com/libero/reviewer-client/pull/22
I'm not how the current builds will be green without this.
=> Fix lint errors

CODE_OF_CONDUCT.md, CONTRIBUTING.md, LICENSE, package.json, yarn.lock
Improves: https://github.com/libero/reviewer/issues/481
Improves: https://github.com/libero/reviewer/issues/482
=> Review split

.env.example, docker-compose.build.yml, docker-compose.yml, scripts/build-config.sh
=> Completed #28: removed use of SERVER_PORT

src/ui/molecules/ManuscriptUpload.test.tsx, test-utils/flushPromises.ts
Closes libero/reviewer-client#30
=> remove flush promises 

docs/adr/browser-testing.md
=> add codeceptjs and webdriverio to the browser test document

.env.example, docker-compose.yml, src/dashboard/components/Dashboard.tsx, src/dashboard/graphql.ts, yarn.lock
Adds reviewer-mocks service to docker-compose and include the startSubmission query for testing purposes.
=> 36 - add mock login service

deployment/nginx.conf.template, src/login/components/JournalAuthRedirect.test.tsx
* fixed trailing slash in nginx proxy rule
* lint fixes
=> add trailing slash to auth and fixed lint

.env.example, docker-compose.yml, src/core/components/App.tsx, src/login/components/Logout.test.tsx, src/login/components/Logout.tsx, src/login/utils/tokenUtils.ts, tests/page-objects/DashboardPage.ts
=> create logout page and connect menu link

.gitignore, Makefile, config/reviewer-mocks/config.example.json, docker-compose.yml
=> changed reviewer-mocks config to use json

Makefile, docker-compose.yml
=> 65 - Make test_browser & setup fixes for running tests locally

.github/workflows/ci.yml, Makefile, README.md
=> 67 clean makefile

.github/workflows/ci.yml
Part of the consolidation of https://github.com/libero/publisher/issues/310
=> Use common script to push Docker image

.github/workflows/ci.yml
Still to complete https://github.com/libero/publisher/issues/310
Follow-up to the [follow-up](https://github.com/libero/reviewer-client/pull/74).
I missed one job as it didn't do any check out :man_facepalming:, but it was the only relevant one as it's the one where the image pushing happens.
=> Check out sources in all jobs

.storybook/webpack.config.js, src/core/utils/auth.ts, src/dashboard/components/SubmissionEntry.tsx, src/ui/atoms/Checkbox.test.tsx, src/ui/molecules/ProgressBar.tsx, webpack.config.js
This should just tidy up the code following a DeepScan check.
=> 76 - Tidy up unused params / imports and always true conditionals

src/core/components/App.tsx, src/core/components/NavBar.test.tsx, src/core/components/NavBar.tsx, src/core/graphql.ts, src/core/providers/AppProvider.tsx, src/core/types.ts, src/login/components/Login.test.tsx, src/login/components/Login.tsx, src/login/stories/Login.stories.tsx, src/ui/molecules/ProfileDropdown.test.tsx, src/ui/molecules/ProfileDropdown.tsx, src/ui/stories/molecules/ProfileDropdown.stories.tsx, tests/Login.browser.ts, tests/page-objects/AppPage.ts
=> call get user after login

.storybook/i18n.ts, src/core/locales/en/article-types.json, src/core/utils/i18n.ts, src/initial-submission/components/ArticleType.test.tsx, src/initial-submission/components/ArticleType.tsx, src/initial-submission/stories/ArticleType.stories.tsx, src/ui/atoms/SelectField.test.tsx, src/ui/atoms/SelectField.tsx
Closes #79 
Added the ArticleType component and altered the SelectField to allow a default value.
=> article type component

README.md, docker-compose.yml, src/dashboard/components/Dashboard.test.tsx, src/dashboard/components/Dashboard.tsx, src/dashboard/components/NoSubmissions.test.tsx, src/dashboard/components/NoSubmissions.tsx, src/dashboard/stories/NoSubmissions.stories.tsx
Adds functionality to the start submission button found on the no submissions screen.
Closes #85
=> 85 start submission mutation

docs/adr/browser-testing.md, docs/adr/form-framework.md
Attempted to put the points we discussed in yesterdays decision meeting into an ADR doc.
Closes #81
=> Form framework ADR

.storybook/preview-body.html, src/core/components/App.tsx, src/core/styles/_global.scss, src/core/styles/_layout.scss, src/dashboard/components/Dashboard.tsx, src/dashboard/components/NoSubmissions.tsx, src/dashboard/stories/Dashboard.stories.tsx, src/dashboard/styles/dashboard.scss, src/dashboard/styles/no_submissions.scss, src/login/components/Login.tsx, src/login/stories/Login.stories.tsx, src/login/styles/login.scss, src/ui/atoms/Footer.tsx, src/ui/atoms/index.ts, src/ui/stories/atoms/AppBar.stories.tsx, src/ui/styles/AppBar.scss, src/ui/styles/Paragraph.scss
=> grid layout

webpack.parts.js
Fixes config being served on every request when client is run with webpack
=> Fix bypass function for serving public config

Makefile, src/dashboard/components/SubmissionEntry.test.tsx, src/ui/atoms/Modal.test.tsx, src/ui/atoms/Modal.tsx, src/ui/molecules/PeoplePickerSelector.test.tsx, src/ui/organisms/PeoplePicker.test.tsx, src/ui/stories/atoms/Modal.stories.tsx, test-utils/appContainer.ts, test-utils/appWrapper.tsx, webpack.parts.js
=> 95 modal upgrade

.github/workflows/ci.yml, package.json
=> add engine constraint

src/initial-submission/components/AuthorDetailsForm.tsx
=> add authosave pattern

.github/workflows/ci.yml, package.json, src/core/components/App.test.tsx, src/core/components/App.tsx, src/core/components/NavBar.test.tsx, src/core/components/NavBar.tsx, src/core/utils/auth.test.ts, src/core/utils/auth.ts, src/core/utils/createApolloClient.ts, webpack.parts.js, yarn.lock
=> Fixes for graphql errors

src/ui/molecules/CoverLetter.test.tsx, src/ui/molecules/CoverLetter.tsx, src/ui/molecules/index.ts, src/ui/stories/molecules/CoverLetter.stories.tsx, src/ui/styles/CoverLetter.scss, src/ui/styles/index.scss
Closes #113 
Realised we already have a MultilineTextField, although Cover Letter doesn't have a label.
This will probably do until we have a rich text editor or we have a textarea atom?
=> Basic cover letter component

src/core/locales/en/ui.json, src/core/styles/_layout.scss, src/core/styles/_mixins.scss, src/core/styles/_typography.scss, src/dashboard/styles/dashboard.scss, src/ui/molecules/FileUpload.test.tsx, src/ui/molecules/MultiFileUpload.test.tsx, src/ui/molecules/MultiFileUpload.tsx, src/ui/molecules/UploadProgress.test.tsx, src/ui/molecules/UploadProgress.tsx, src/ui/molecules/index.ts, src/ui/stories/molecules/MultiFileUpload.stories.tsx, src/ui/stories/molecules/UploadProgress.stories.tsx, src/ui/styles/MultiFileUpload.scss, src/ui/styles/PeoplePicker.scss, src/ui/styles/UploadProgress.scss, src/ui/styles/index.scss
closes #134 
adds styled supporting upload component as MultiFileUpload ui component
=> 134 supporting upload

Makefile, README.md, config/config.infra.docker.example.json, config/config.infra.example.json, config/config.infra.local.example.json, package.json, src/dashboard/styles/dashboard.scss
Closes #140 
* fixes styling on dashboard button container
* adds config.infra.local.example.json and updates Makefile for easer local dev experience
=> fix misplaced new submission button

package.json, yarn.lock
=> Correct types

src/core/graphql.ts, src/initial-submission/components/AuthorDetailsForm.tsx, src/initial-submission/components/FileDetailsForm.test.tsx, src/initial-submission/components/FileDetailsForm.tsx, src/initial-submission/components/SubmissionWizard.test.tsx, src/initial-submission/graphql.ts, test-utils/setup.ts
closes #137 
Hooks up mutation call to coverLetter textarea and sets initialValues value as default.
=> 137 - save files page

src/dashboard/components/Dashboard.tsx, src/dashboard/components/SubmissionEntry.tsx, src/dashboard/graphql.ts, src/initial-submission/components/AuthorDetailsForm.tsx, src/initial-submission/components/Routes.tsx, src/initial-submission/components/SubmissionWizard.test.tsx, src/initial-submission/components/SubmissionWizard.tsx, src/initial-submission/graphql.ts, src/initial-submission/types.ts, yarn.lock
=> Fix initial submission bugs

src/initial-submission/components/AuthorDetailsForm.tsx, src/initial-submission/graphql.ts
Part of https://github.com/libero/reviewer/issues/620
=> Rename saveDetailsPage to saveAuthorPage

src/initial-submission/components/FileDetailsForm.test.tsx, src/initial-submission/components/FileDetailsForm.tsx, src/initial-submission/components/SubmissionWizard.tsx, src/initial-submission/graphql.ts
Introduce mutation to controller and begin building state object for Upload Component
=> 571 - upload controller

src/core/locales/en/ui.json, src/initial-submission/components/FileDetailsForm.test.tsx, src/initial-submission/components/FileDetailsForm.tsx, src/ui/molecules/FileUpload.tsx, src/ui/molecules/MultiFileUpload.test.tsx, src/ui/molecules/MultiFileUpload.tsx, src/ui/stories/molecules/FileUpload.stories.tsx
Adds manuscript upload state for validation errors which are file size and file type.
closes libero/reviewer#628
=> 628 file error state

src/core/styles/_typography.scss, src/dashboard/components/ArticleType.test.tsx, src/ui/atoms/SelectField.test.tsx, src/ui/atoms/SelectField.tsx, src/ui/styles/SelectField.scss
Closes libero/reviewer#644
Spacing for select component.
=> 644 select restructure

src/initial-submission/components/FileDetailsForm.test.tsx, src/initial-submission/components/FileDetailsForm.tsx, src/initial-submission/graphql.ts, src/initial-submission/types.ts, src/ui/molecules/CoverLetter.tsx
=> 656 graphql fixes

src/initial-submission/components/FileDetailsForm.test.tsx, src/initial-submission/components/FileDetailsForm.tsx, src/ui/molecules/MultiFileUpload.test.tsx, src/ui/molecules/MultiFileUpload.tsx, src/ui/stories/molecules/MultiFileUpload.stories.tsx, src/ui/styles/MultiFileUpload.scss
This adds the component to the page and passes and onUpload callback which adds files to the local state object.
Part 2 will integrate the mutation and synchronous request queue.
=> add MultifileUpload component to Files form page (Part 1)

src/ui/molecules/UploadProgress.test.tsx, src/ui/molecules/UploadProgress.tsx, src/ui/stories/molecules/UploadProgress.stories.tsx, src/ui/styles/UploadProgress.scss
=> add spinner animation to upload progress

src/initial-submission/components/SubmissionWizard.tsx
Fix the remount issue.
Closes libero/reviewer#678
=> replace component with render on the submissionWizard

.github/semver.yml, .github/workflows/ci.yml
- update libero/scripts submodule
- switch to retag-and-push.sh
- add semver tagging github workflow
=> build: switch to retag-and-push.sh

src/core/utils/createApolloClient.ts
Might fix https://github.com/libero/reviewer/runs/549182924?check_suite_focus=true
=> Attempts to fix issue with review-client umbrella repo 

src/initial-submission/components/AuthorDetailsForm.test.tsx, src/initial-submission/components/AuthorDetailsForm.tsx, src/initial-submission/components/DetailsForm.test.tsx, src/initial-submission/components/DetailsForm.tsx, src/initial-submission/components/FileDetailsForm.test.tsx, src/initial-submission/components/FileDetailsForm.tsx, src/initial-submission/hooks/useAutoSave.ts, src/initial-submission/utils/autosave-decorator.ts
Closes libero/reviewer#688
Replaces the use of AutosaveDecorator with a custom auto save hook so we don't call save on initial render.
=> 668 - autosave bug

deployment/nginx.conf.template
closes https://github.com/libero/reviewer/issues/694
=> Add x-forwarded-for

src/initial-submission/components/FileDetailsForm2.test.tsx
=> Add Unit Tests for Uploading supporting files

Dockerfile.application, Dockerfile.source
Pin:
- nginx to stable-alpine
- node to 12-alpine
=> pin base images

src/initial-submission/components/FileDetailsForm.test.tsx, src/initial-submission/components/FileDetailsForm.tsx, src/initial-submission/components/FileDetailsForm2.test.tsx, src/initial-submission/graphql.ts, src/initial-submission/types.ts, src/ui/molecules/MultiFileUpload.test.tsx, src/ui/molecules/MultiFileUpload.tsx, src/ui/stories/molecules/MultiFileUpload.stories.tsx
=> delete supporting file

src/initial-submission/components/FileDetailsForm.test.tsx, src/ui/molecules/FileUpload.test.tsx, src/ui/molecules/FileUpload.tsx
closes https://github.com/libero/reviewer/issues/766
=> Add spinner until progress comes in

src/initial-submission/components/FileDetailsForm.tsx, src/initial-submission/components/FileDetailsForm2.test.tsx, src/initial-submission/hooks/useSupportingFileHook.ts, src/ui/molecules/MultiFileUpload.test.tsx, src/ui/molecules/MultiFileUpload.tsx
- validate file size and error state on files that are to big.
- deletable error state items
Closes libero/reviewer#721
Closes libero/reviewer#775
=> 721 - Validation error state on supporting files

src/initial-submission/components/SubmissionWizard.tsx
=> 800 - allow partial cache updates to trigger rerender

src/core/locales/en/wizard-form.json, src/initial-submission/components/AuthorDetailsForm.tsx, src/initial-submission/components/DetailsForm.tsx, src/initial-submission/components/FileDetailsForm.tsx, yarn.lock
Closes libero/reviewer#712
-Will address details form steps validation after bugs are fixed
=> 712 - validation

src/initial-submission/components/DetailsForm.tsx, src/initial-submission/graphql.ts, src/initial-submission/types.ts
=> Use suggestions

src/core/styles/_typography.scss, src/ui/atoms/Checkbox.tsx, src/ui/styles/Checkbox.scss
=> Use line-height consisent with checkbox-field__input height

src/initial-submission/components/AuthorDetailsForm.tsx, src/initial-submission/components/DetailsForm.tsx, src/initial-submission/components/FileDetailsForm.tsx, src/initial-submission/components/SubmissionWizard.test.tsx, src/initial-submission/components/SubmissionWizard.tsx, src/initial-submission/stories/FileDetailsForm.stories.tsx
=> Validate on navigation

src/initial-submission/components/DetailsForm.test.tsx, src/initial-submission/components/DetailsForm.tsx, src/ui/atoms/ExpandingTextField.test.tsx, src/ui/atoms/ExpandingTextField.tsx, src/ui/atoms/index.ts, src/ui/stories/atoms/ExandingTextField.stories.tsx, src/ui/styles/ExpandingTextField.scss, src/ui/styles/MultilineTextField.scss, src/ui/styles/index.scss
Adds a fixed row expanding text area for the title filed.
closes libero/reviewer#224
=> 224 - expanding title Component

src/initial-submission/components/SubmissionWizard.tsx
Closes https://github.com/libero/reviewer/issues/828
=> removes error log state modified after mount

src/initial-submission/components/AuthorDetailsForm.test.tsx, src/initial-submission/components/FileDetailsForm.test.tsx
Closes libero/reviewer#847
Unit test validation of Author and File fields.
=> 847 validation unit tests

src/core/components/App.tsx, src/dashboard/components/SubmissionEntry.tsx, src/initial-submission/hooks/useAutoSave.ts, src/ui/molecules/BurgerMenu.tsx, src/ui/molecules/CoverLetter.tsx, src/ui/molecules/PersonPod.tsx, src/ui/molecules/SearchField.tsx, webpack.parts.js
tidy up some files to reduce bundle size
=> shrink bundle size

src/initial-submission/components/AuthorDetailsForm.tsx, src/initial-submission/components/SubmissionWizard.tsx, src/initial-submission/styles/AuthorDetails.scss, tests/browser-tests/Login.browser.ts, tests/page-objects/AuthorDetailsPage.ts, tests/page-objects/index.ts
closes https://github.com/libero/reviewer/issues/850
=> 850 create author details page - testCafe

config/nginx-proxies/nginx.dev.conf, config/nginx-proxies/nginx.test.conf
=> Allow websockets from route for react debugging

src/core/locales/en/wizard-form.json, src/initial-submission/components/EditorsForm.tsx, src/initial-submission/components/SubmissionWizard.tsx, src/initial-submission/graphql.ts, src/initial-submission/types.ts, src/ui/organisms/PeoplePicker.tsx
Initial Editors Page, It has most of the functionality but is missing a lot of the connections from mocks and submission and the expanding email field.
the libero/reviewer#609 ticket will be completed after those are complete.
=> 609 editors page

tests/browser-tests/Login.browser.ts, tests/page-objects/NavigationPane.ts
Following https://github.com/libero/reviewer/issues/856
=> Add username check on nav bar

src/login/components/Logout.test.tsx, src/login/components/Logout.tsx, src/ui/molecules/ProfileDropdown.tsx, tests/browser-tests/Login.browser.ts, tests/page-objects/NavigationPane.ts
=> Logout test for nav bar test

src/ui/styles/PersonPod.scss, src/ui/styles/Pod.scss
Closes https://github.com/libero/reviewer/issues/885
=> 885 people pod overflow v2

src/core/locales/en/ui.json, src/core/styles/_mixins.scss, src/initial-submission/components/EditorsForm.tsx, src/initial-submission/components/SubmissionWizard.tsx, src/initial-submission/hooks/useAutoSave.ts, src/ui/atoms/TextField.tsx, src/ui/molecules/ExpandingEmailField.test.tsx, src/ui/molecules/ExpandingEmailField.tsx, src/ui/molecules/index.ts, src/ui/stories/molecules/ExpandingEmailField.stories.tsx, src/ui/styles/ExpandingEmailField.scss, src/ui/styles/index.scss
Closes libero/reviewer#233
Adds an expanding name email component to our UI components
=> Expanding email field

src/core/locales/en/wizard-form.json, src/initial-submission/components/EditorsForm.test.tsx, src/initial-submission/components/EditorsForm.tsx, src/ui/molecules/ExpandingEmailField.test.tsx, src/ui/molecules/ExpandingEmailField.tsx
closes libero/reviewer#895
Adds an Expanding Email component for suggested reviewers on editors page.
=> 895 - suggested reviewers

.github/workflows/ci.yml, Makefile
- firefox is already bundled into testcafe image
- run sequentially to avoid test interaction
Closes: https://github.com/libero/reviewer/issues/915
=> run firefox in addition to chromium

src/ui/styles/PeoplePicker.scss
Closes libero/reviewer#943 
Tested locally
=> Fix pod width sizing

src/core/locales/en/wizard-form.json, src/initial-submission/components/EditorsForm.test.tsx, src/initial-submission/components/EditorsForm.tsx, src/ui/molecules/ExcludedToggle.tsx
Closes https://github.com/libero/reviewer/issues/894
=> 894 exclude reviewer

src/initial-submission/components/EditorsForm.test.tsx, src/initial-submission/components/EditorsForm.tsx, src/initial-submission/types.ts, src/ui/molecules/ExpandingEmailField.test.tsx, src/ui/molecules/ExpandingEmailField.tsx, src/ui/stories/molecules/ExpandingEmailField.stories.tsx
=> 955 - Expanding email field controlled

tests/browser-tests/Login.browser.ts, tests/page-objects/EditorPage.ts, tests/page-objects/index.ts
closes https://github.com/libero/reviewer/issues/853
=> 853 create editors test page v2

src/core/locales/en/wizard-form.json, src/initial-submission/components/EditorsForm.test.tsx, src/initial-submission/components/EditorsForm.tsx, src/initial-submission/graphql.ts, src/initial-submission/hooks/useAutoSave.ts, src/initial-submission/types.ts, src/ui/organisms/PeoplePicker.tsx, src/ui/styles/ExcludedToggle.scss, src/ui/styles/ExpandingEmailField.scss, src/ui/styles/PeoplePicker.scss, tests/browser-tests/Login.browser.ts, tests/page-objects/EditorPage.ts
closes libero/reviewer#896
Adds opposed reviewers section to editors page
=> 896 opposed reviewers

src/core/styles/_mixins.scss, src/ui/styles/Modal.scss, src/ui/styles/PeoplePicker.scss
=> fix grid layout for the people picker modal

.github/workflows/ci.yml, Makefile, tests/page-objects/EditorPage.ts
Closes libero/reviewer#1010  and
Closes libero/reviewer#1012
=> remove people picker search from happy path

src/initial-submission/components/EditorsForm.test.tsx, src/initial-submission/components/EditorsForm.tsx
=> 1015 -  min max opposed

src/initial-submission/components/EditorsForm.tsx, src/ui/organisms/PeoplePicker.test.tsx, src/ui/organisms/PeoplePicker.tsx
=> add option to hide external people picker label

src/core/locales/en/wizard-form.json, src/initial-submission/components/EditorsForm.test.tsx, src/initial-submission/components/EditorsForm.tsx, src/initial-submission/styles/EditorsForm.scss, src/initial-submission/styles/index.scss
=> 545 diversity text

src/static-pages/components/PageNavigation.tsx, src/static-pages/styles/page-navigation.scss
closes https://github.com/libero/reviewer/issues/1036
=> Fix layout of left hand menu

src/dashboard/components/Dashboard.exceptions.test.tsx, src/dashboard/components/Dashboard.tsx
Closes https://github.com/libero/reviewer/issues/990
=> Handle possible undefined

src/core/locales/en/ui.json, src/initial-submission/components/EditorsForm.tsx, src/ui/atoms/Modal.test.tsx, src/ui/atoms/Modal.tsx, src/ui/molecules/PeoplePickerSelector.test.tsx, src/ui/molecules/PeoplePickerSelector.tsx, src/ui/molecules/PersonPod.test.tsx, src/ui/molecules/PersonPod.tsx, src/ui/molecules/SelectedPeopleList.tsx, src/ui/organisms/PeoplePicker.test.tsx, src/ui/organisms/PeoplePicker.tsx, src/ui/stories/molecules/PeoplePickerSelector.stories.tsx, src/ui/stories/molecules/PersonPod.stories.tsx, src/ui/stories/organisms/PeoplePicker.stories.tsx
=> 1040 - fix people picker initially selected overriding local selections

src/core/locales/en/wizard-form.json, src/initial-submission/components/DisclosureForm.test.tsx, src/initial-submission/components/DisclosureForm.tsx, src/initial-submission/components/SubmissionWizard.test.tsx, src/initial-submission/components/SubmissionWizard.tsx, src/initial-submission/graphql.ts
=> 611 add submit modal

README.md
Please let me know if the url to the browsertest results doesn't work for you.
=> doc: fix saucelabs badge and link to results

src/initial-submission/components/DisclosureForm.test.tsx, src/initial-submission/components/DisclosureForm.tsx, src/ui/atoms/Checkbox.tsx, src/ui/styles/Checkbox.scss
closes libero/reviewer#1059
+ styling fixes
=> 1059 disclosure consent validation

src/core/components/App.tsx, src/core/locales/en/survey.json, src/core/styles/index.scss, src/core/utils/i18n.ts, src/initial-submission/components/SubmissionWizard.tsx, src/survey/components/Routes.tsx, src/survey/components/Survey.test.tsx, src/survey/components/Survey.tsx, src/survey/graphql.ts, src/survey/styles/survey.scss, src/survey/types.ts
=> 624 survey page

src/initial-submission/styles/SubmissionWizard.scss
=> add button margin

src/initial-submission/components/Routes.tsx, src/initial-submission/components/SubmissionWizard.tsx, src/initial-submission/components/ThankYouPage.test.tsx, src/initial-submission/components/ThankYouPage.tsx, src/initial-submission/styles/ThankYouPage.scss
https://github.com/libero/reviewer/issues/626
=> Refactor thank you as per xpub routes

tests/browser-tests/Login.browser.ts, tests/page-objects/DisclosurePage.ts, tests/page-objects/index.ts
=> add disclosure page object

src/core/locales/en/wizard-form.json, src/initial-submission/components/EditorsForm.tsx, src/ui/molecules/SelectedPeopleList.test.tsx
Closes https://github.com/libero/reviewer/issues/1099
=> Align validation

src/dashboard/components/SubmissionEntry.test.tsx, src/dashboard/components/SubmissionEntry.tsx, src/dashboard/components/SubmissionList.test.tsx, src/dashboard/stories/SubmissionEntry.stories.tsx, src/dashboard/stories/SubmissionList.stories.tsx, src/dashboard/stories/storyUtils.ts, src/dashboard/utils/dateTimeDiffToText.test.ts, src/dashboard/utils/dateTimeDiffToText.ts, src/initial-submission/components/AuthorDetailsForm.test.tsx, src/initial-submission/components/DetailsForm.test.tsx, src/initial-submission/components/DisclosureForm.test.tsx, src/initial-submission/components/EditorsForm.test.tsx, src/initial-submission/components/FileDetailsForm.test.tsx, src/initial-submission/components/FileDetailsForm2.test.tsx, src/initial-submission/components/ThankYouPage.test.tsx, src/initial-submission/stories/FileDetailsForm.stories.tsx, src/initial-submission/types.ts
Fixes the date displaying on dashboard
Closes libero/reviewer#1009
=> 1009 - fix date problems

tests/page-objects/DisclosurePage.ts
Add missing functionality to previous PR
=> add mising submit functionality

src/core/utils/auth.test.ts, src/core/utils/auth.ts, src/initial-submission/components/Routes.test.tsx, src/login/utils/tokenUtils.ts
Closes https://github.com/libero/reviewer/issues/993
=> 993 handle obsolete tokens

src/initial-submission/components/EditorsForm.tsx
=> 1058 - manually call validate when changing people picker values

src/ui/molecules/ProfileDropdown.test.tsx, src/ui/molecules/ProfileDropdown.tsx, tests/page-objects/NavigationPane.ts
closes libero/reviewer#1113
removes profile role
=> 1013 - remove role from profile menu

Makefile, src/core/components/NavBar.test.tsx, src/core/components/NavBar.tsx, tests/page-objects/NavigationPane.ts
Closes https://github.com/libero/reviewer/issues/1112
=> Nav bar with static links

browsertests.Dockerfile, package.json, tests/browser-tests/Login.browser.ts, tests/browser-tests/Minimal.browser.ts, yarn.lock
Closes https://github.com/libero/reviewer/issues/1002
=> Try await for react render on browser tests

src/ui/styles/ProfileDropdown.scss
=> 1114 - profile menu styling fixes

Makefile, src/ui/molecules/FileUpload.tsx
Closes https://github.com/libero/reviewer/issues/1118
=> Show correct status

src/initial-submission/components/DetailsForm.tsx, src/ui/atoms/SelectField.tsx
Fixes https://github.com/libero/reviewer/issues/1119
=> Prevent more than 2 subject selection

src/core/locales/en/article-type.json, src/core/styles/_config.scss, src/core/styles/_typography.scss, src/dashboard/components/ArticleType.tsx, src/ui/styles/Button.scss
- Fix ORCID button hover colour 
- Fix background colour of links
- Fix typo on article type
- Fix button cursor
=> misc ux fixes from call

src/core/locales/en/article-type.json, src/dashboard/components/ArticleType.tsx
Closes https://github.com/libero/reviewer/issues/1115
=> Use correct article types

src/core/locales/en/dashboard.json, src/core/locales/en/thank-you-page.json, src/dashboard/components/Dashboard.tsx, src/dashboard/components/SubmissionList.tsx, src/dashboard/styles/dashboard.scss, src/initial-submission/components/ThankYouPage.tsx
=> implement ux changes

src/initial-submission/styles/DetailsForm.scss, src/ui/styles/SelectField.scss
=> 1137 article type ux

src/login/utils/tokenUtils.test.ts, src/login/utils/tokenUtils.ts
related to libero/reviewer#1132
=> Token in param

src/core/locales/en/wizard-form.json, src/initial-submission/components/DetailsForm.tsx, src/initial-submission/styles/DetailsForm.scss
=> fix details page

src/ui/molecules/FileUpload.test.tsx, src/ui/molecules/FileUpload.tsx
un-pushed commits from local branch for https://github.com/libero/reviewer-client/pull/330 relates to https://github.com/libero/reviewer/issues/1138
=> 1138 files page styles missing

src/core/locales/en/dashboard.json, src/dashboard/components/SubmissionEntry.test.tsx, src/dashboard/components/SubmissionEntry.tsx, src/dashboard/components/SubmissionList.test.tsx, src/dashboard/components/SubmissionList.tsx
=> add translations for dashboard

README.md, src/dashboard/components/Dashboard.test.tsx, src/dashboard/components/Dashboard.tsx, src/dashboard/components/SubmissionEntry.test.tsx, src/dashboard/components/SubmissionEntry.tsx, src/dashboard/graphql.ts, src/initial-submission/graphql.ts
=> add last step functionality

src/core/locales/en/dashboard.json, src/dashboard/components/Dashboard.test.tsx, src/dashboard/components/SubmissionEntry.test.tsx, src/dashboard/components/SubmissionEntry.tsx, src/dashboard/graphql.ts
Solves the following issues from  https://github.com/libero/reviewer/issues/1162
>  remove trashcan and delete action
submission isn't clickable after submitted
Status displayed: "Submitted: Check e-mail"
=> Addresses issues from #1162

src/core/locales/en/wizard-form.json, src/initial-submission/components/FileDetailsForm.tsx, src/initial-submission/utils/validationSchemas.ts, src/ui/molecules/FileUpload.test.tsx, src/ui/molecules/FileUpload.tsx
=> Add file validation

src/core/locales/en/author-guide.json, src/static-pages/components/Fees.tsx
As per https://github.com/elifesciences/elife-xpub/issues/2446
=> remove blog post links

src/ui/styles/Modal.scss
=> 1189 modal styling

src/core/components/App.tsx, src/core/locales/en/ui.json, src/core/styles/_config.scss, src/ui/atoms/CookieBanner.test.tsx, src/ui/atoms/CookieBanner.tsx, src/ui/atoms/index.ts, src/ui/hooks/useCookieNotification.test.tsx, src/ui/hooks/useCookieNotification.ts, src/ui/styles/CookieBanner.scss, src/ui/styles/index.scss, tests/page-objects/LoginPage.ts
=> 619 add cookie banner

src/core/locales/en/contact-us.json, src/static-pages/components/ProductionStaff.tsx
Closes https://github.com/libero/reviewer/issues/1074
=> Update production staff

src/ui/styles/CoverLetter.scss
Closes https://github.com/libero/reviewer/issues/1202
=> Fix cover letter styles

tests/browser-tests/Login.browser.ts, tests/page-objects/DisclosurePage.ts, tests/page-objects/SurveyPage.ts, tests/page-objects/index.ts
=> add page object and fix disclosure page

src/core/locales/en/author-guide.json, tests/browser-tests/Login.browser.ts, tests/page-objects/StaticPage.ts, tests/page-objects/StaticPages.ts, tests/page-objects/index.ts
=> add static page objects and tests

src/core/components/App.tsx, src/dashboard/components/Routes.tsx, src/initial-submission/components/Routes.tsx
Closes https://github.com/libero/reviewer/issues/1234
=> code splitting bundles

config/nginx-proxies/nginx.ci.conf, config/nginx-proxies/nginx.ci.localhost.conf, config/nginx-proxies/nginx.dev.conf, config/nginx-proxies/nginx.test.conf, src/login/components/Login.tsx
=> 888 auth login

tests/browser-tests/Login.browser.ts, tests/page-objects/index.ts, tests/page-objects/validationHelper.ts
[run-saucelabs]
Closes libero/reviewer#957
=> 957 extract form validation

tests/browser-tests/HappyPath.browser.ts, tests/browser-tests/Login.browser.ts, tests/browser-tests/Navigation.browser.ts, tests/browser-tests/StaticPages.browser.ts, tests/browser-tests/Validation.browser.ts, tests/page-objects/DisclosurePage.ts, tests/page-objects/NavigationHelper.ts, tests/page-objects/index.ts
[run-saucelabs]
Quick refactor to make writing the browser tests easier.
=> Refactor browser test

docker-compose.ci.localhost.yml, docker-compose.ci.yml, src/ui/molecules/FileUpload.tsx, tests/browser-tests/CompletePath.browser.ts, tests/browser-tests/HappyPath.browser.ts, tests/page-objects/AuthorDetailsPage.ts, tests/page-objects/DashboardPage.ts, tests/page-objects/DetailsPage.ts, tests/page-objects/DisclosurePage.ts, tests/page-objects/EditorPage.ts, tests/page-objects/FilesPage.ts, tests/page-objects/NavigationHelper.ts, tests/page-objects/SurveyPage.ts, tests/page-objects/ThankYouPage.ts, tests/page-objects/index.ts, tests/test-data/mockApiData/reviewingEditors.json, tests/test-data/mockApiData/seniorEditors.json
=> Complete path browsertests

.eslintrc.js, package.json, src/initial-submission/components/SubmissionWizard.tsx, src/initial-submission/hooks/useSupportingFileHook.ts, src/ui/atoms/Checkbox.tsx, src/ui/molecules/Menu.tsx, yarn.lock
Closes https://github.com/libero/reviewer/issues/1242
=> Remove create react app linting

tests/browser-tests/Dashboard.browser.ts
=> add test for deleting a submission

package.json, src/dashboard/components/SubmissionList.tsx
closes https://github.com/libero/reviewer/issues/1285
=> fix lint scripts + add sort order

public/locales/en/ui.json, src/index.tsx, src/ui/molecules/FileUpload.tsx
Closes https://github.com/libero/reviewer/issues/1241
=> 1241 indeterminate spinner

docker-compose.yml, src/ui/atoms/TickIcon.tsx, src/ui/atoms/UploadIcon.tsx, src/ui/styles/PersonPod.scss, src/ui/styles/Pod.scss
=> fix people picker ux

public/locales/en/common.json, src/core/components/NavBar.tsx, src/static-pages/components/AuthorGuide.tsx, src/static-pages/components/ContactUs.tsx, src/static-pages/components/ReviewerGuide.tsx, src/static-pages/styles/page-navigation.scss
closes https://github.com/libero/reviewer/issues/1300
=> Static pages menu problems

src/core/styles/_typography.scss, src/static-pages/components/ArticleTypes.tsx, src/static-pages/components/ContactUsElife.tsx, src/static-pages/components/EditorialProcess.tsx, src/static-pages/components/EditorialStaff.tsx, src/static-pages/components/Fees.tsx, src/static-pages/components/FullSubmission.tsx, src/static-pages/components/InitialSubmission.tsx, src/static-pages/components/JournalFAQs.tsx, src/static-pages/components/JournalMetrics.tsx, src/static-pages/components/JournalPolicies.tsx, src/static-pages/components/PageNavigation.tsx, src/static-pages/components/PostDecision.tsx, src/static-pages/components/ProductionStaff.tsx, src/static-pages/components/ReviewProcess.tsx, src/static-pages/components/ReviewingPolicies.tsx, src/static-pages/components/RevisedSubmission.tsx, src/static-pages/components/WritingReview.tsx, src/static-pages/styles/page-navigation.scss, src/static-pages/styles/required-info-table.scss, src/static-pages/styles/static-page.scss
Closes https://github.com/libero/reviewer/issues/1298
=> Fix typography issues along with layout issues

src/ui/molecules/PeoplePickerSelector.tsx, src/ui/molecules/SearchField.tsx, src/ui/stories/molecules/SearchField.stories.tsx
=> fix people picker search

src/core/styles/index.scss
=> add normalize comment

src/initial-submission/graphql.ts
=> add status to mutation return so it updates on the dashboard

tests/page-objects/DashboardPage.ts
Attempts to fix https://github.com/libero/reviewer/runs/1022927316?check_suite_focus=true
=> Use .exists rather than .visible for elements

src/initial-submission/components/AuthorDetailsForm.test.tsx, src/initial-submission/components/AuthorDetailsForm.tsx
Closes libero/reviewer#1211
(ignore incorrect ticket number on branch name)
=> add validation to the pre-fill function

tests/page-objects/DashboardPage.ts, tests/page-objects/FilesPage.ts
Part of https://github.com/libero/reviewer/issues/1340
=> Ensure more reliable delete test

src/initial-submission/components/EditorsForm.test.tsx, src/initial-submission/components/EditorsForm.tsx
Closes https://github.com/libero/reviewer/issues/1073
=> Add Deputy editors to senior editor instance of People Picker

src/dashboard/components/Dashboard.tsx, src/dashboard/components/SubmissionEntry.tsx, src/dashboard/styles/dashboard.scss
=> fix styling for small screens

src/dashboard/components/Dashboard.test.tsx, src/dashboard/components/Dashboard.tsx, src/dashboard/components/SubmissionEntry.test.tsx, src/dashboard/components/SubmissionEntry.tsx, src/dashboard/components/SubmissionList.test.tsx, src/dashboard/components/SubmissionList.tsx, src/dashboard/graphql.ts, src/dashboard/stories/SubmissionEntry.stories.tsx, src/dashboard/stories/SubmissionList.stories.tsx, src/initial-submission/types.ts
=> 1347 no article type

config/nginx-proxies/nginx.ci.conf, config/nginx-proxies/nginx.ci.localhost.conf, config/nginx-proxies/nginx.dev.conf, config/nginx-proxies/nginx.test.conf, src/login/components/Logout.test.tsx, src/login/components/Logout.tsx, tests/browser-tests/Authentication.browser.ts, tests/page-objects/LoginPage.ts
=> 1264 orcid page object

tests/browser-tests/Authentication.browser.ts, tests/browser-tests/ExtendedAuthentication.browser.ts
Ensure more stable test on umbrella repo
=> Fix test issue with logout redirect

src/login/components/Logout.test.tsx, src/login/components/Logout.tsx
replace resetStore with clearStore as resetStore refetches data.
=> replace cache clear with proper api call

tests/browser-tests/Authentication.browser.ts, tests/browser-tests/Dashboard.browser.ts, tests/browser-tests/ExtendedAuthentication.browser.ts, tests/browser-tests/HappyPath.browser.ts, tests/browser-tests/ReplaceAndRemoveFiles.browser.ts, tests/test-entry.sh
Part of https://github.com/libero/reviewer/issues/923 - more sensible and stable test suite for staging
=> Tests for staging

tests/browser-tests/Authentication.browser.ts, tests/browser-tests/HappyPath.browser.ts, tests/browser-tests/Minimal.browser.ts, tests/test-entry.sh
Follow up to https://github.com/libero/reviewer-client/pull/406
=> Follow up to https://github.com/libero/reviewer-client/pull/406

src/ui/styles/CoverLetter.scss
Fixes https://github.com/libero/reviewer/issues/1384
=> Fix differences in cover letter spacing between xpub and reviewer 

tests/browser-tests/Dashboard.browser.ts, tests/browser-tests/ExtendedAuthentication.browser.ts, tests/page-objects/DashboardPage.ts, tests/page-objects/LoginPage.ts
Fixes for the authentication based browser tests when ran over staging (new ORCID steps).
=> Acceptance browsertest changes

tests/page-objects/AuthorDetailsPage.ts, tests/page-objects/EditorPage.ts
Closes https://github.com/libero/reviewer/issues/1390
=> Use prefill + assert spinner is not there on editor page

tests/browser-tests/ExtendedAuthentication.browser.ts
=> add await for journal page

src/static-pages/styles/static-page.scss
Closes https://github.com/libero/reviewer/issues/1405
=> Fix layout issues with static pages

src/dashboard/components/Dashboard.tsx, src/dashboard/styles/dashboard.scss, src/ui/atoms/index.ts
=> add spinner

src/core/components/App.tsx, src/ui/styles/AppBar.scss
Fixes https://github.com/libero/reviewer/issues/1404
=> Add app loading spinner

src/dashboard/components/Dashboard.tsx
=> fix boolean

public/locales/en/contact-us.json
=> use iiif to make sure the images are not massive

src/initial-submission/components/EditorsForm.tsx, src/initial-submission/components/SubmissionWizard.test.tsx, src/initial-submission/components/SubmissionWizard.tsx, src/initial-submission/styles/EditorsForm.scss, src/initial-submission/styles/SubmissionWizard.scss, src/ui/molecules/PeoplePickerSelector.test.tsx, src/ui/molecules/PeoplePickerSelector.tsx, src/ui/molecules/SelectedPeopleList.tsx, src/ui/organisms/PeoplePicker.test.tsx, src/ui/organisms/PeoplePicker.tsx, src/ui/stories/molecules/PeoplePickerSelector.stories.tsx, src/ui/stories/molecules/SelectedPeopleList.stories.tsx, src/ui/stories/organisms/PeoplePicker.stories.tsx
Closes https://github.com/libero/reviewer/issues/1403 but also removes the "loading..." text around in the app
=> Near xPub parity loading spinners

src/initial-submission/components/EditorsForm.test.tsx, src/initial-submission/components/EditorsForm.tsx
Closes https://github.com/libero/reviewer/issues/1408
=> Sort editors

src/initial-submission/components/EditorsForm.tsx, tests/page-objects/EditorPage.ts
Hopefully closes https://github.com/libero/reviewer/issues/1411 as found here https://github.com/libero/reviewer-client/runs/1117623991
=> Attempt to have a more stable test

public/locales/en/ui.json, public/locales/en/wizard-form.json, src/initial-submission/components/DetailsForm.tsx
closes libero/reviewer#1415
closes libero/reviewer#1419
=> 1415 error banner typo

src/ui/styles/CoverLetter.scss
Closes https://github.com/libero/reviewer/issues/1412
=> Fix overflow issues with prosemirror

public/locales/en/wizard-form.json, src/initial-submission/components/EditorsForm.test.tsx, src/initial-submission/components/FileDetailsForm.tsx, src/initial-submission/types.ts, src/initial-submission/utils/validationSchemas.ts, tests/page-objects/EditorPage.ts
Display validation error for supporting files if next is pressed before uploads are done.
Closes https://github.com/libero/reviewer/issues/1414
=> Display validation error for supporting files if next is pressed before uploads are done

src/initial-submission/components/FileDetailsForm.test.tsx, src/initial-submission/components/FileDetailsForm.tsx, src/ui/molecules/FileUpload.tsx
=> add filetype restriction to file picker

src/initial-submission/utils/validationSchemas.ts
=> add validation rule to reject empty p tag

src/core/components/App.tsx, src/login/components/Login.tsx, tests/page-objects/EditorPage.ts
Closes https://github.com/libero/reviewer/issues/1427 and https://github.com/libero/reviewer/issues/1424
=> Error bar should not persist when moving pages 

src/initial-submission/components/DetailsForm.test.tsx, src/initial-submission/components/DetailsForm.tsx
=> 1426 empty second cosubmission box prevents submission

src/initial-submission/components/DisclosureForm.tsx
=> consent validation bug

public/locales/en/ui.json, src/ui/molecules/FileUpload.test.tsx, src/ui/molecules/FileUpload.tsx, tests/browser-tests/Validation.browser.ts, tests/page-objects/FilesPage.ts
Adds custom empty error state for manuscript upload
=> 1345 manuscript validation

src/initial-submission/components/DetailsForm.tsx, src/ui/molecules/Toggle.tsx
Closes https://github.com/libero/reviewer/issues/1427
=> Fix bug with values not being set correctly due to watch

src/initial-submission/styles/DetailsForm.scss, src/ui/styles/SelectField.scss
Closes https://github.com/libero/reviewer/issues/1346
=> Styling issues on details page

public/locales/en/login.json, src/login/styles/login.scss
=> 1344 login styling

src/static-pages/styles/static-page.scss
Closes https://github.com/libero/reviewer/issues/1440
=> Remove excess whitespace from author guide / initial submission

src/dashboard/components/Dashboard.tsx
Closes https://github.com/libero/reviewer/issues/1445
=> Replace history to remove query params

public/locales/en/article-type.json, src/dashboard/components/ArticleType.tsx
Closes https://github.com/libero/reviewer/issues/1446 and closes https://github.com/libero/reviewer/issues/1444
=> correct links and styles

src/initial-submission/components/AuthorDetailsForm.test.tsx, src/initial-submission/components/EditorsForm.test.tsx, src/initial-submission/components/EditorsForm.tsx, src/ui/molecules/ExpandingEmailField.test.tsx, src/ui/molecules/ExpandingEmailField.tsx
Following on from https://github.com/libero/reviewer-client/pull/452
=> Better email trimming and additional tests 

public/index.html, src/core/utils/config.ts
=> Add hotjar

tests/page-objects/AuthorDetailsPage.ts
closes elifesciences/issues#6316
=> change email used to prevent bounceback issues on umbrella repo tests

public/locales/en/author-guide.json
=> fix: missing link in author guide

.storybook/i18n.ts
This fixes elifesciences/issues#6641
=> fix: storybook fails to build due to invalid imports

public/locales/en/wizard-form.json, src/initial-submission/components/AuthorDetailsForm.tsx, src/initial-submission/styles/AuthorDetails.scss
This progresses elifesciences/issues#6724
=> fix: add missing form title to author details page

package.json, public/locales/en/author-guide.json, public/locales/en/wizard-form.json, src/initial-submission/components/FileDetailsForm.test.tsx, src/initial-submission/components/FileDetailsForm.tsx, src/initial-submission/utils/validationSchemas.ts, tests/browser-tests/Validation.browser.ts, yarn.lock
@Cooryd Can you have a quick look and see if I have removed what I need to remove for cover letter not to be mandatory. I think I have removed everything but would like for you to check and advise.
=> Removing cover letter being mandatory

.github/workflows/ci.yml, Makefile, package.json, public/index.html, testcafe.json, tests/browser-tests/Authentication.browser.ts, tests/browser-tests/ExtendedAuthentication.browser.ts, tests/browser-tests/Navigation.browser.ts, tests/browser-tests/StaticPages.browser.ts, tests/page-objects/CookieBanner.ts, tests/page-objects/LoginPage.ts, tests/page-objects/NavigationHelper.ts, tests/page-objects/index.ts, tests/test-entry.sh
=> fix: update browser tests to check and dismiss the new cookie banner

public/index.html
as per https://github.com/elifesciences/issues/issues/7346
=> replace google analytics code with new google tag manager
